### ISSUE TITLE
Is there an adopters file?

### ISSUE THREAD

**Issue by alexellis** [docsifyjs/awesome-docsify#119]
This repo has a list of sub-projects, but do you also want a list of projects or companies that are using docsify? Might be nice to collect them to show what can be done in an adopters file?

**Comment by anikethsaha** [comment]
That would be great. Yeah we can show their logos and name. But as of now , I am only familiar with few of them. We can create a list here and then we can show that in readme.

**Comment by jthegedus** [comment]
Hey @alexellis fan of your work. How will this differ to the [Enterprise Usage section](https://github.com/docsifyjs/awesome-docsify#enterprise-usage)?

**Comment by alexellis** [comment]
There's a massive difference between enterprise usage and end-users. Or are you only interested in large company adoption? 

I also found that section confusing. You may want to add a subheading for what belongs there. It looked a lot like extensions / side-projects on the main project.

**Comment by jthegedus** [comment]
>There's a massive difference between enterprise usage and end-users

Agreed, there is.

>Or are you only interested in large company adoption

We're interested in showcasing everyone, not just large companies.

---

I guess I'm just unclear on how the Showcase and Enterprise Usage sections would differ from end-users. Is it just company logos?

**Comment by alexellis** [comment]
There doesn't seem to be a fit for https://docs.inlets.dev in your file. I'm also considering using it for https://k3sup.dev and maybe https://get-arkade.dev

I like it mainly because it uses Markdown and doesn't need me to be a designer.

In the OpenFaaS project we let folks give a sentence or two about their usage for insights. 

https://github.com/openfaas/faas/blob/master/ADOPTERS.md

Make sure you have written permission from any legal entities involved before collecting logos as we do on openfaas.com

**Comment by jthegedus** [comment]
IMO they would go in the Showcase section, but @anikethsaha likes your idea so I will leave them to decide where these would go.

**Comment by anikethsaha** [comment]
I am more into adding the logos instead of just name but dont really want me or someone from the team to write for permission from each one as it would eat our time/effort for just logos. 

But yea we can make the current one better.

cc @docsifyjs/reviewers thoughts.
