### ISSUE TITLE
Docsify websequence diagrams plugin

### ISSUE THREAD

**Issue by aajiwani** [docsifyjs/awesome-docsify#123]
Hey great people,

Thanks for the awesome implementation around Docsify; It has changed my life.

I have recently created a plugin that helps converting `websequence diagrams` text to appropriate images, fetching it from the given [API](https://www.websequencediagrams.com/embedding.html). Can you see if this is appropriate and can add as the list of plugins under docsify, if possible?

[here](https://www.npmjs.com/package/websequencediagrams-docsify) is the npm package for my plugin, it includes how to use it as the readme.

**Comment by sy-records** [comment]
Sure. You can just submit the PR.
