### ISSUE TITLE
A plugin used for  annotation 

### ISSUE THREAD

**Issue by wellcomez** [docsifyjs/awesome-docsify#151]
https://github.com/wellcomez/docsify-highlight

**Comment by sy-records** [comment]
You can submit a PR directly.

**Comment by trusktr** [comment]
@wellcomez Hello! Nice. Please do submit a PR. Also if you can add a little more info to your README with more full screenshot(s) that would be nice. :)

**Comment by wellcomez** [comment]
@trusktr  what is pr meaning and how to submit pr. i don't know .

**Comment by Koooooo-7** [comment]
Close by long unresponsive.
Instead, plz send a PR to add your awesome project in ur awesome list thx !


> what is pr meaning and how to submit pr. i don't know .

@wellcomez  Hi, you can just folk this project and create a `PULL REQUEST` to this project.
