### ISSUE TITLE
Docker Image

### ISSUE THREAD

**Issue by Sujaykumarh** [docsifyjs/awesome-docsify#159]
docsify docker image 

i couldn't find a docker image for docsify so built one with example repo

- [Docker image](https://github.com/Sujaykumarh/docsify-docker) - Docker image
- [Docker example](https://github.com/Sujaykumarh/docsify-docker-example) - Docker image example repo

i do not know which category to add this to, suggestion to create **_Docker_** section for any future docker images from community

```markdown
- Docker
    - [image-name](repo-url) - desc  
```

- Docker
  - [sujaykumarh/docsify](https://github.com/Sujaykumarh/docsify-docker) - A simple docker container for docsify

**Comment by Koooooo-7** [comment]
Thx for ur input! 👍 
I think you can add it in `Community Resources` section.

**Comment by Sujaykumarh** [comment]
Okay. Will do

**Comment by Sujaykumarh** [comment]
#162
