### ISSUE TITLE
Prettier in docsify!

### ISSUE THREAD

**Issue by KonghaYao** [docsifyjs/awesome-docsify#166]
Hi, I recently create a prettier plugin for docsify to formmater my code in website. So I make this [docsify-prettier](https://github.com/KonghaYao/docsify-prettier), now we can have a better code reading environment!

**Comment by sy-records** [comment]
Feel free to send a PR here.

**Comment by trusktr** [comment]
@KonghaYao Hello! That is awesome! Please do add it to the list.

**Comment by Koooooo-7** [comment]
Close by long unresponsive.
Instead, plz send a PR to add your awesome project in ur awesome list thx !
