### ISSUE TITLE
A Plugin: docsify-to-queryparam-markdown-engine

### ISSUE THREAD

**Issue by ShowMeBaby** [docsifyjs/awesome-docsify#185]
demo1Url: https://retrocode.io/#/?custom=1&mdurl=https://docsify.js.org/README.md

demo2Url: https://retrocode.io/#/%E6%8A%80%E5%B7%A7/Markdown%E8%AF%AD%E6%B3%95?custom=1

demo3Url: https://retrocode.io/#/?mdurl=https://docsify.js.org/README.md

eng: Use docsify as markdown engine, get markdown link from queryparam and render

zh: 把docsify当作 markdown引擎 渲染query参数**mdurl**传递的远程markdown文件,并通过插件配置隐藏footer/sidebar等标签(custom=1开启/隐藏).
我用来在移动端及微信小程序的webview内置一些文档,或者临时浏览markdown远程markdown文件.

github: https://github.com/ShowMeBaby/docsify-to-queryparam-markdown-engine

npm: https://www.npmjs.com/package/docsify-to-queryparam-markdown-engine

**Comment by sy-records** [comment]
Feel free to submit a PR.
