### ISSUE TITLE
plugin for lightweight and modern animated terminal window from markdown

### ISSUE THREAD

**Issue by sxin0** [docsifyjs/awesome-docsify#261]
[https://github.com/sxin0/docsify-termynal](https://github.com/sxin0/docsify-termynal)

````
```term
$ php -v
PHP 7.3.23 (cli) (built: Apr 20 2022 15:59:45) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.23, Copyright (c) 1998-2018 Zend Technologies

# 这个一个选择 (y/n) $ y
// 这是注释
$ pip install fastapi
>> 100%
```
````

![Video_2023-05-22_162348_AdobeExpress](https://github.com/sxin0/docsify-termynal/assets/29392026/6cbc0179-c27c-4c0d-9dc1-7f9993a1850a)

**Comment by sy-records** [comment]
cool. You can submit a PR.
