### ISSUE TITLE
docsify-markmap.js

### ISSUE THREAD

**Issue by rcqed** [docsifyjs/awesome-docsify#266]
- [docsify-markmap.js](https://github.com/rcqed/docsify-markmap.js) - 🪄🪄🪄Create a new Markmap instance and render the code content on your Docsify

**Comment by sy-records** [comment]
You can submit a PR.

**Comment by rcqed** [comment]
This is my first time to PR, I add docsify-markmap.js at the end of the plugin, how to request?

**Comment by rcqed** [comment]
#267
