### ISSUE TITLE
Created a plugin to run Phaser javascript code in a Docsify MD

### ISSUE THREAD

**Issue by luisalvesmartins** [docsifyjs/awesome-docsify#57]
Hope you find it useful: https://github.com/luisalvesmartins/docsifyPhaser

**Comment by anikethsaha** [comment]
@luisalvesmartins this is great.
submit a PR to add this

**Comment by jthegedus** [comment]
I believe this was closed by #58

**Comment by anikethsaha** [comment]
> I believe this was closed by #58

yup
