### ISSUE TITLE
webview for awesome-docsify

### ISSUE THREAD

**Issue by boopathikumar018** [docsifyjs/awesome-docsify#79]
to create webview for awesome-docsify

**Comment by anikethsaha** [comment]
webview for what ? mobile ?

**Comment by boopathikumar018** [comment]
Website instead of viewing in GitHub

**Comment by jthegedus** [comment]
There is a site that exists that takes a owner/repo pair and renders as a website, I cannot remember the URL or name of it though.

**Comment by anikethsaha** [comment]
feel free to do it and submit a PR to add a link to readme for `awesome-docsify`

**Comment by jthegedus** [comment]
I'm pretty sure it is just a crawler of GitHub looking for awesome lists and then has some CSS to render the readmes nicely. It isn't anything we would need to do. 

Just saying specifically making a site with Docsify to view the Docsify awesome-list is a bit pointless, especially since the list is already included with Docsify https://docsify.js.org/#/awesome

**Comment by anikethsaha** [comment]
> I'm pretty sure it is just a crawler of GitHub looking for awesome lists and then has some CSS to render the readmes nicely. It isn't anything we would need to do.
> 
> Just saying specifically making a site with Docsify to view the Docsify awesome-list is a bit pointless, especially since the list is already included with Docsify https://docsify.js.org/#/awesome

yes true, 👍 ,
I forgot about https://docsify.js.org/#/awesome. 

Thanks @boopathikumar018 for your time 👍

**Comment by boopathikumar018** [comment]
That’s great I didn’t see that. Thanks 👍🏻

**Comment by jthegedus** [comment]
I also forgot about it until I got to the end of writing my reply 😅  Thanks for you input @boopathikumar018 please keep ideas and improvements coming!

**Comment by boopathikumar018** [comment]
Sure thanks for your time ✌🏻
