### ISSUE TITLE
自荐 CS-Wiki

### ISSUE THREAD

**Issue by Veal98** [docsifyjs/awesome-docsify#85]
📃 文档地址：[https://veal98.gitee.io/cs-wiki/#/](https://veal98.gitee.io/cs-wiki/#/)
📦 github仓库地址：[https://github.com/Veal98/CS-Wiki](https://github.com/Veal98/CS-Wiki)
<br/>

![](https://gitee.com/veal98/images/raw/master/img/20200507102605.png)

**Comment by jthegedus** [comment]
Please submit a PR with the summary in English as Google translate didn't translate this well for me to understand, sorry.

**Comment by Koooooo-7** [comment]
Feel free to send a PR here, f.e [showcase](https://github.com/docsifyjs/awesome-docsify#showcase).
